### ISSUE TITLE
ADD has abstract[FILTER] to PubMed queries?

### ISSUE THREAD

**Issue by cstubben** [neilfws/PubMed#1]
I think you should add  "has abstract"[FILTER] to the PubMed queries for the "novel" findings.  For example, in 1974 only 5% of citations have abstracts compared to 86% in 2014.

**Comment by neilfws** [comment]
This sounds like a good suggestion. Another alternative would be to search only in titles. I'll investigate and amend accordingly.

**Comment by neilfws** [comment]
OK; latest code and output amended with the suggestion.
